/**
 * PlanTab.jsx — Multi-week mesocycle plan with week/full views.
 * Props: { workout, history, coach }
 * Data source: coach.mesocycle (generated by useCoachState + trainingEngine)
 * PlanTab never calls generateTrainingPlan directly — it reads mesocycle.weeks[selectedWeekIndex].
 */
import { useState, useEffect, useMemo } from 'react';
import { BarChart, Bar, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { generateMesocycle, PHASE_COLORS, PHASE_LABELS, calcTrainingLoad, assessDetraining, TYPE_COLOR, SESSION_INTENTS, DAY_LABELS } from '../../core/trainingEngine.js';
import { fmtDateDM, fmtDateDMY, localDateIso } from '../../core/format.js';
import { Card, CardLabel } from './OverviewTab.jsx';

const OPENAI_KEY     = import.meta.env.VITE_OPENAI_API_KEY ?? '';
const AI_PLAN_MODEL  = 'gpt-4o';

const OPENWEATHER_API_KEY = import.meta.env.VITE_OPENWEATHER_API_KEY ?? '';

function windDirection(deg) {
  if (deg == null || Number.isNaN(deg)) return '—';
  const dirs = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NNW'];
  const idx = Math.round((((deg % 360) + 360) % 360) / 22.5) % 16;
  return dirs[idx];
}

function extractWorkoutCoords(workout) {
  const points = workout?.timeSeries ?? [];
  const point = points.find(p => Number.isFinite(p?.lat) && Number.isFinite(p?.lon));
  return point ? { lat: point.lat, lon: point.lon } : null;
}

function pickDailyForecastFrom3h(list = [], dayIndex = 0) {
  if (!list.length) return null;
  const target = new Date();
  target.setHours(12, 0, 0, 0);
  target.setDate(target.getDate() + dayIndex);
  const targetMs = target.getTime();
  const sameDay = list.filter(item => {
    const dt = new Date((item.dt ?? 0) * 1000);
    return dt.getFullYear() === target.getFullYear() &&
           dt.getMonth()    === target.getMonth()    &&
           dt.getDate()     === target.getDate();
  });
  if (!sameDay.length) return null;
  let best = sameDay[0];
  let bestDiff = Math.abs(((best.dt ?? 0) * 1000) - targetMs);
  for (let i = 1; i < sameDay.length; i++) {
    const diff = Math.abs(((sameDay[i].dt ?? 0) * 1000) - targetMs);
    if (diff < bestDiff) { best = sameDay[i]; bestDiff = diff; }
  }
  const windMs = Number(best?.wind?.speed ?? 0);
  return {
    tempC:        Math.round(best?.main?.temp ?? 0),
    windMs:       parseFloat(windMs.toFixed(1)),
    windKmh:      Math.round(windMs * 3.6),
    windDeg:      best?.wind?.deg ?? null,
    windDir:      windDirection(best?.wind?.deg),
    weatherLabel: best?.weather?.[0]?.main ?? '',
  };
}

// ── Phase context banner ──────────────────────────────────────────────────────

export function PlanContextBanner({ meta, mesocycleMeta }) {
  const dt    = meta.detraining;
  const load  = meta.load;
  const phase = meta.phase;

  const phaseColor = {
    full_restart: '#ef4444', base_rebuild: '#f97316', significant: '#fbbf24',
    moderate: '#a3e635', slight: '#60a5fa', overreached: '#ef4444',
    active: '#4ade80', too_easy: '#a78bfa',
  }[phase] ?? '#6b7280';

  const tsbColor = load.tsb > 5 ? '#4ade80' : load.tsb < -15 ? '#ef4444' : '#fbbf24';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-3)' }}>
      <div style={{
        background: `${phaseColor}10`, border: `1px solid ${phaseColor}30`,
        borderRadius: 'var(--r-md)', padding: 'var(--sp-3) var(--sp-4)',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <div>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>TRAINING PHASE</div>
          <div style={{ fontSize: 13, color: phaseColor, fontWeight: 600 }}>{dt.label}</div>
          {dt.daysSince < 999 && (
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
              Last workout: {dt.daysSince === 0 ? 'today' : `${dt.daysSince} days ago`}
            </div>
          )}
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: 9, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 4 }}>WEEK VOLUME</div>
          <div style={{ fontSize: 20, fontWeight: 600, color: phaseColor, fontFamily: 'var(--font-display)' }}>~{meta.targetWeekKm} km</div>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
            base {meta.baseKm} km × {Math.round(100 / meta.baseKm * meta.targetWeekKm)}%
          </div>
        </div>
      </div>
      {(load.ctl > 0 || load.atl > 0) && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 'var(--sp-2)' }}>
          {[
            { label: 'CTL (fitness)',    value: load.ctl.toFixed(1), color: '#60a5fa', sub: 'avg TE/42 days' },
            { label: 'ATL (load)',       value: load.atl.toFixed(1), color: '#f97316', sub: 'avg TE/7 days'  },
            { label: 'TSB (freshness)', value: (load.tsb > 0 ? '+' : '') + load.tsb.toFixed(1), color: tsbColor, sub: load.tsb > 5 ? 'fresh' : load.tsb < -15 ? 'fatigue' : 'neutral' },
          ].map(item => (
            <div key={item.label} style={{
              background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)',
              borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)',
            }}>
              <div style={{ fontSize: 9, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>{item.label}</div>
              <div style={{ fontSize: 18, fontWeight: 600, color: item.color, fontFamily: 'var(--font-display)', lineHeight: 1 }}>{item.value}</div>
              <div style={{ fontSize: 9, color: 'var(--text-dim)', marginTop: 2 }}>{item.sub}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Confirm modal ─────────────────────────────────────────────────────────────

function ConfirmModal({ title, body, confirmLabel, confirmColor = '#f97316', onConfirm, onCancel }) {
  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 600,
      background: 'rgba(0,0,0,0.55)', backdropFilter: 'blur(3px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    }} onClick={onCancel}>
      <div
        onClick={e => e.stopPropagation()}
        style={{
          background: 'var(--bg-surface)', border: '1px solid var(--border-mid)',
          borderRadius: 'var(--r-lg)', padding: 'var(--sp-5)',
          width: 'min(380px, 90vw)', display: 'flex', flexDirection: 'column', gap: 'var(--sp-4)',
          boxShadow: '0 8px 40px rgba(0,0,0,0.5)',
        }}
      >
        <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>{title}</div>
        <div style={{ fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.6 }}>{body}</div>
        <div style={{ display: 'flex', gap: 'var(--sp-3)', justifyContent: 'flex-end' }}>
          <button onClick={onCancel} style={{
            background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--r-sm)', padding: '6px 16px',
            fontSize: 12, color: 'var(--text-secondary)', cursor: 'pointer',
          }}>Cancel</button>
          <button onClick={() => { onConfirm(); onCancel(); }} style={{
            background: `${confirmColor}18`, border: `1px solid ${confirmColor}55`,
            borderRadius: 'var(--r-sm)', padding: '6px 16px',
            fontSize: 12, color: confirmColor, fontWeight: 600, cursor: 'pointer',
          }}>{confirmLabel}</button>
        </div>
      </div>
    </div>
  );
}

// ── Session tags ──────────────────────────────────────────────────────────────

function sessionTags(day) {
  if (day.aiCues?.length > 0) return day.aiCues;
  const t = day.type;
  const hi = (day.intensity ?? 0) >= 88;
  if (t === 'rest')     return ['rest day'];
  if (t === 'recovery') return ['Z1', 'HR <65%', 'easy'];
  if (t === 'aerobic')  return ['Z2', 'HR 65–75%', 'conversational'];
  if (t === 'long')     return ['Z2', 'endurance', 'easy–moderate'];
  if (t === 'tempo')    return ['Z3', 'threshold', 'comfortably hard'];
  if (t === 'interval') return hi ? ['Z5', 'VO₂max', 'maximal'] : ['Z4', 'FTP', 'structured'];
  if (t === 'test')     return ['assessment', 'calibration'];
  return [];
}

// ── Day card ─────────────────────────────────────────────────────────────────

function DayCard({ day, weather, index, revealed, compliance }) {
  const highlight = day.current;
  const compBadge = compliance ? {
    nailed_it:  { color: '#4ade80', label: 'Nailed it' },
    close:      { color: '#fbbf24', label: 'Close' },
    off_target: { color: '#f97316', label: 'Off target' },
    skipped:    { color: '#ef4444', label: 'Skipped' },
  }[compliance.verdict] : null;

  return (
    <div style={{
      background:    highlight ? `${day.color}0d` : 'var(--bg-overlay)',
      border:        `1px solid ${highlight ? `${day.color}35` : 'var(--border-subtle)'}`,
      borderRadius:  'var(--r-md)', padding: 'var(--sp-3) var(--sp-4)',
      display: 'flex', flexDirection: 'column', gap: 'var(--sp-2)',
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div style={{ display: 'flex', gap: 'var(--sp-3)', alignItems: 'flex-start', flex: 1 }}>
          <div style={{ minWidth: 28 }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: highlight ? day.color : 'var(--text-secondary)', fontFamily: 'var(--font-mono)', lineHeight: 1.2 }}>{day.day}</div>
            {(day.dateIso || day.date) && <div style={{ fontSize: 9, color: 'var(--text-dim)', fontFamily: 'var(--font-mono)' }}>{fmtDateDM(day.dateIso ?? day.date)}</div>}
          </div>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
              <span style={{ fontSize: 13, color: highlight ? 'var(--text-primary)' : 'var(--text-secondary)' }}>
                {day.aiTitle ?? day.label}
              </span>
              {day.current && (
                <span style={{ fontSize: 9, color: day.color, fontFamily: 'var(--font-mono)', background: `${day.color}18`, border: `1px solid ${day.color}40`, borderRadius: 4, padding: '2px 6px', letterSpacing: '0.06em' }}>TODAY</span>
              )}
              {compBadge && (
                <span style={{ fontSize: 9, color: compBadge.color, fontFamily: 'var(--font-mono)', background: `${compBadge.color}18`, border: `1px solid ${compBadge.color}40`, borderRadius: 4, padding: '2px 6px' }}>{compBadge.label}</span>
              )}
            </div>
            {(() => { const tags = sessionTags(day); return tags.length > 0 && (
              <div style={{ marginTop: 4, display: 'flex', gap: 4, flexWrap: 'wrap' }}>
                {tags.map((tag, i) => (
                  <span key={i} style={{
                    fontSize: 9, color: 'var(--text-secondary)', background: 'var(--bg-raised)',
                    border: '1px solid var(--border-subtle)', borderRadius: 3,
                    padding: '2px 6px', fontFamily: 'var(--font-mono)',
                  }}>{tag}</span>
                ))}
              </div>
            ); })()}
            {(day.aiWhy || day.desc) && (
              <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 4, lineHeight: 1.5 }}>
                {day.aiWhy && <div>{day.aiWhy}</div>}
                {day.desc && <div style={{ marginTop: day.aiWhy ? 3 : 0 }}>{day.desc}</div>}
              </div>
            )}
            {weather && (
              <div style={{ fontSize: 10, color: 'var(--text-secondary)', marginTop: 4, fontFamily: 'var(--font-mono)' }}>
                {weather.tempC}°C · wind {weather.windKmh} km/h {weather.windDir}
              </div>
            )}
          </div>
        </div>
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <div style={{ fontSize: 10, color: day.color, fontFamily: 'var(--font-mono)', textTransform: 'uppercase' }}>{day.type}</div>
          {day.targetKm > 0 && <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>~{day.targetKm} km</div>}
          {compBadge && compliance?.details?.distanceDelta && (
            <div style={{ fontSize: 9, color: 'var(--text-dim)', fontFamily: 'var(--font-mono)' }}>
              {compliance.details.distanceDelta.actual?.toFixed(1)} km actual
            </div>
          )}
        </div>
      </div>
      <div style={{ height: 4, background: 'var(--bg-raised)', borderRadius: 2, overflow: 'hidden' }}>
        <div style={{
          height: '100%', width: revealed ? `${day.intensity}%` : '0%',
          background: highlight ? `linear-gradient(90deg,${day.color}88,${day.color})` : day.color,
          borderRadius: 2, transition: revealed ? 'width 0.6s var(--ease-snappy)' : 'none',
          transitionDelay: revealed ? `${index * 60 + 200}ms` : '0ms',
          boxShadow: highlight ? `0 0 6px ${day.color}55` : 'none',
        }} />
      </div>
    </div>
  );
}

// ── Week card (full plan view) ────────────────────────────────────────────────

function WeekCard({ week, isCurrent, isSelected, onClick }) {
  const phase = week.isRecovery ? 'recovery' : week.phase;
  const phaseColor = PHASE_COLORS[phase] ?? '#6b7280';
  const phaseLabel = week.isRecovery ? 'Recovery' : (PHASE_LABELS[phase] ?? phase);

  const sessionIcons = week.days.map(d => ({
    rest:     '—', recovery: '◦', aerobic: '●', tempo: '▲',
    interval: '★', long: '◉', test: '◈',
  }[d.type] ?? '●'));

  return (
    <div
      onClick={onClick}
      style={{
        background:   isSelected ? `${phaseColor}15` : 'var(--bg-overlay)',
        border:       `1px solid ${isCurrent ? phaseColor : isSelected ? `${phaseColor}60` : 'var(--border-subtle)'}`,
        borderRadius: 'var(--r-md)', padding: 'var(--sp-3)',
        cursor: 'pointer', minWidth: 120, flexShrink: 0,
        transition: 'all var(--t-base) var(--ease-snappy)',
        position: 'relative',
      }}
    >
      {isCurrent && (
        <div style={{ position: 'absolute', top: -8, left: '50%', transform: 'translateX(-50%)', fontSize: 9, fontFamily: 'var(--font-mono)', color: phaseColor, background: 'var(--bg-base)', padding: '1px 6px', border: `1px solid ${phaseColor}`, borderRadius: 4 }}>NOW</div>
      )}
      <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>Week {week.weekIndex + 1}</div>
      <div style={{ fontSize: 11, color: phaseColor, fontWeight: 600, marginBottom: 4 }}>{phaseLabel}</div>
      <div style={{ fontSize: 12, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', marginBottom: 6 }}>{week.targetKm} km</div>
      <div style={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
        {sessionIcons.map((icon, i) => (
          <span key={i} style={{ fontSize: 8, color: week.days[i] ? (PHASE_COLORS[week.days[i].type] ?? phaseColor) : 'var(--text-dim)' }}>{icon}</span>
        ))}
      </div>
    </div>
  );
}

// ── Main PlanTab ──────────────────────────────────────────────────────────────

function todayIsoStr() { return localDateIso(); }
function tomorrowIsoStr() { return localDateIso(new Date(Date.now() + 86400000)); }

export function PlanTab({ workout: w, history, coach }) {
  const [viewMode, setViewMode] = useState('week');
  const [hasManualPlanControls, setHasManualPlanControls] = useState(false);
  const [planSport, setPlanSport] = useState(() => {
    const t = coach?.mesocycle?.meta?.sport ?? coach?.profile?.targetSport;
    return (t === 'running' || t === 'cycling' || t === 'mixed') ? t : 'mixed';
  });
  // 'auto' = current Monday (legacy default), 'today', 'tomorrow', 'custom'
  const [startMode, setStartMode] = useState('auto');
  const [customDate, setCustomDate] = useState(() => todayIsoStr());

  const effectiveStartDate = useMemo(() => {
    if (startMode === 'today')    return todayIsoStr();
    if (startMode === 'tomorrow') return tomorrowIsoStr();
    if (startMode === 'custom')   return customDate;
    return null; // auto → Monday snap inside generateMesocycle
  }, [startMode, customDate]);

  const histWorkouts = history?.history ?? [];

  // When DB mesocycle arrives, keep sport selector in sync with the stored plan
  // until the user manually changes plan controls.
  useEffect(() => {
    if (hasManualPlanControls) return;
    const savedSport = coach?.mesocycle?.meta?.sport;
    if (savedSport === 'running' || savedSport === 'cycling' || savedSport === 'mixed') {
      setPlanSport(savedSport);
    }
  }, [coach?.mesocycle?.meta?.sport, hasManualPlanControls]);

  // Get or generate mesocycle for display.
  // DB is only updated via explicit Regenerate click.
  // Until then, control changes can preview a local (unsaved) plan.
  const mesocycle = useMemo(() => {
    const saved = coach?.mesocycle;
    const savedSport = saved?.meta?.sport ?? coach?.profile?.targetSport ?? 'mixed';
    const isSportChanged = planSport !== savedSport;

    // AI-generated plans always take priority — never overwrite with template preview.
    if (saved?.weeks?.length && saved?.meta?.aiGenerated) return saved;

    // Use persisted template plan when controls match the saved "auto + sport" context.
    if (saved?.weeks?.length && startMode === 'auto' && !isSportChanged) return saved;

    // Preview mode (unsaved): local generation from current controls.
    const profile = coach?.profile ?? {};
    const sportProfile = { ...profile, targetSport: planSport !== 'mixed' ? planSport : (profile.targetSport ?? 'running') };
    return generateMesocycle(sportProfile, histWorkouts, effectiveStartDate);
  }, [coach?.mesocycle, coach?.profile, histWorkouts, planSport, effectiveStartDate, startMode]);

  const [aiPlanState, setAiPlanState] = useState({ loading: false, error: '' });
  // activeMesocycle = coach.mesocycle (persisted, either template or AI) or local preview
  const activeMesocycle = mesocycle;

  const [selectedWeekIndex, setSelectedWeekIndex] = useState(() => mesocycle?.currentWeekIndex ?? 0);

  // Keep selectedWeekIndex in sync when mesocycle changes
  useEffect(() => {
    if (activeMesocycle?.currentWeekIndex != null) {
      setSelectedWeekIndex(activeMesocycle.currentWeekIndex);
    }
  }, [activeMesocycle?.currentWeekIndex]);

  // Lazy-enrich future/past weeks when the user navigates to them
  useEffect(() => {
    const week = activeMesocycle?.weeks?.[selectedWeekIndex];
    if (!week) return;
    // Skip if already enriched (any day has an aiTitle)
    if (week.days?.some(d => d.aiTitle)) return;
    // Skip if it's the current week — regenerateMesocycle handles that
    if (selectedWeekIndex === currentWeekIdx) return;
    if (!activeMesocycle?.meta?.aiGenerated) coach?.enrichWeekDays?.(selectedWeekIndex, week.days, null, histWorkouts, planSport);
  }, [selectedWeekIndex]); // eslint-disable-line react-hooks/exhaustive-deps

  const displayedWeek  = activeMesocycle?.weeks?.[selectedWeekIndex] ?? null;
  const currentWeekIdx = activeMesocycle?.currentWeekIndex ?? 0;
  const isPreviewMode  = selectedWeekIndex !== currentWeekIdx;
  const todayIso       = localDateIso();

  const plan = useMemo(() => {
    if (!displayedWeek) return [];
    return displayedWeek.days.map((d, i) => ({
      ...d,
      current: d.dateIso === todayIso,
    }));
  }, [displayedWeek, todayIso]);

  // Compliance per day (from history)
  const complianceByDate = useMemo(() => {
    const map = {};
    for (const w of histWorkouts) {
      if (w.complianceResult) map[w.date] = w.complianceResult;
    }
    return map;
  }, [histWorkouts]);

  // Weekly compliance summary
  const weeklyCompliance = useMemo(() => {
    if (!displayedWeek) return null;
    const plannedDays = displayedWeek.days.filter(d => d.type !== 'rest');
    const completed = plannedDays.filter(d => histWorkouts.some(w => w.date === d.dateIso));
    if (!plannedDays.length) return null;
    return {
      completionRate: Math.round((completed.length / plannedDays.length) * 100),
      completed: completed.length,
      planned: plannedDays.length,
    };
  }, [displayedWeek, histWorkouts]);

  const coords = extractWorkoutCoords(w);

  // ── Weather ─────────────────────────────────────────────────────────────────
  const savedCity = (() => { try { return localStorage.getItem('plan_weather_city') || ''; } catch { return ''; } })();
  const [weatherSource, setWeatherSource] = useState(() => savedCity ? 'city' : 'workout');
  const [cityInput, setCityInput]         = useState(savedCity);
  const [cityQuery, setCityQuery]         = useState(savedCity);
  const [weather, setWeather]             = useState({ loading: false, error: '', days: [], location: '' });

  // Debounce city input → cityQuery (saves on each commit, fetches after 800 ms idle)
  useEffect(() => {
    const t = setTimeout(() => {
      const next = cityInput.trim();
      if (!next) return;
      try { localStorage.setItem('plan_weather_city', next); } catch {}
      setCityQuery(next);
    }, 800);
    return () => clearTimeout(t);
  }, [cityInput]);

  useEffect(() => {
    if (!OPENWEATHER_API_KEY) return;
    const ctrl = new AbortController();
    async function fetchForecast() {
      setWeather(prev => ({ ...prev, loading: true, error: '' }));
      try {
        let lat, lon;
        if (weatherSource === 'workout' && coords) {
          lat = coords.lat; lon = coords.lon;
        } else if (weatherSource === 'city' && cityQuery.trim()) {
          const geoRes  = await fetch(`https://api.openweathermap.org/geo/1.0/direct?q=${encodeURIComponent(cityQuery.trim())}&limit=1&appid=${OPENWEATHER_API_KEY}`, { signal: ctrl.signal });
          const geoData = await geoRes.json();
          if (!geoData?.length) throw new Error('City not found');
          lat = geoData[0].lat; lon = geoData[0].lon;
        } else {
          setWeather({ loading: false, error: '', days: [], location: '' });
          return;
        }
        const res  = await fetch(`https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&units=metric&appid=${OPENWEATHER_API_KEY}`, { signal: ctrl.signal });
        const data = await res.json();
        const list = Array.isArray(data?.list) ? data.list : [];
        const days = Array.from({ length: 7 }, (_, i) => pickDailyForecastFrom3h(list, i)).filter(Boolean);
        setWeather({ loading: false, error: '', days, location: data?.city?.name || (weatherSource === 'city' ? cityQuery.trim() : 'Workout location') });
      } catch (e) {
        if (e.name === 'AbortError') return;
        setWeather({ loading: false, error: e.message || 'Weather load error', days: [], location: '' });
      }
    }
    fetchForecast();
    return () => ctrl.abort();
  }, [coords?.lat, coords?.lon, weatherSource, cityQuery]);

  const [revealed, setRevealed] = useState(false);
  useEffect(() => { const t = setTimeout(() => setRevealed(true), 80); return () => clearTimeout(t); }, []);

  // ── AI plan generation ────────────────────────────────────────────────────────

  const generateAIPlan = async () => {
    if (!OPENAI_KEY) { setAiPlanState({ loading: false, error: 'No OpenAI API key configured.' }); return; }
    setAiPlanState({ loading: true, error: '' });

    const profile      = coach?.profile ?? {};
    const load         = calcTrainingLoad(histWorkouts);
    const dt           = assessDetraining(histWorkouts);
    const recentSummary = [...histWorkouts]
      .sort((a, b) => b.date.localeCompare(a.date))
      .slice(0, 24)
      .map(w => {
        const durationSec = w.duration?.active ?? w.duration?.elapsed ?? w.duration_s ?? 0;
        const durationMin = Math.round(durationSec / 60);
        const distKm      = ((w.distance ?? 0) / 1000).toFixed(1);
        const sport       = w.sport ?? w.sportLabel ?? 'workout';
        const te          = (w.trainingEffect?.aerobic ?? 0).toFixed(1);
        const hr          = w.heartRate?.avg ? `, HR ${w.heartRate.avg} bpm` : '';
        return `${w.date}: ${sport}, ${distKm} km, ${durationMin} min${hr}, TE ${te}`;
      })
      .join('\n') || 'No recent workouts';

    // Mirror the same next-Monday snap that generateMesocycle uses for 'auto' mode
    const startIso = (() => {
      if (effectiveStartDate) return effectiveStartDate;
      const today = new Date();
      const dow = today.getDay(); // 0=Sun, 1=Mon
      const daysToNextMon = dow === 1 ? 7 : (8 - dow) % 7 || 7;
      const mon = new Date(today);
      mon.setDate(today.getDate() + daysToNextMon);
      return localDateIso(mon);
    })();
    const startLabel = startMode === 'auto'     ? `${startIso} (current week Monday)`
                     : startMode === 'today'    ? `${startIso} (today)`
                     : startMode === 'tomorrow' ? `${startIso} (tomorrow)`
                     : `${startIso} (custom date)`;
    const sport    = profile.targetSport ?? planSport ?? 'cycling';
    const avgSpeed = sport === 'cycling' ? 25 : sport === 'running' ? 10 : 15;

    const systemPrompt = `You are an elite endurance coach. Generate a personalized 16-week training mesocycle as JSON.

ATHLETE PROFILE:
- Sport: ${sport}
- Goal: ${profile.primaryGoal ?? profile.goal ?? 'general fitness improvement'}
- Goal event date: ${profile.goalDate ?? 'none'}
- Weekly training hours available: ${profile.weeklyHours ?? 6}h
- FTP: ${profile.ftp ? profile.ftp + ' W' : 'unknown'}
- LTHR: ${profile.lthr ? profile.lthr + ' bpm' : 'unknown'}
- VO2max: ${profile.vo2max ?? 'unknown'}
- Weight: ${profile.weightKg ? profile.weightKg + ' kg' : 'unknown'}
- Height: ${profile.heightCm ? profile.heightCm + ' cm' : 'unknown'}
- Age: ${profile.age ?? (profile.birthday ? (() => { const d=new Date(profile.birthday),t=new Date(); let a=t.getFullYear()-d.getFullYear(); if(t.getMonth()-d.getMonth()<0||(t.getMonth()===d.getMonth()&&t.getDate()<d.getDate()))a--; return a; })() : 'unknown')}
- Experience level: ${profile.experienceLevel ?? 'intermediate'}

CURRENT FITNESS STATE:
- CTL (42-day chronic fitness): ${load.ctl.toFixed(1)}
- ATL (7-day acute load): ${load.atl.toFixed(1)}
- TSB (freshness = CTL - ATL): ${load.tsb.toFixed(1)}
- Detraining status: ${dt.label} (${dt.daysSince < 999 ? dt.daysSince + ' days since last workout' : 'no history'})

RECENT TRAINING LOG (last 24 sessions):
${recentSummary}

OUTPUT RULES:
- Return ONLY valid JSON, no prose outside it
- 16 weeks total, 7 days each (Mo through Su)
- "type" must be one of: rest, recovery, aerobic, tempo, interval, long, test
- "intensity": rest=0, recovery=15, aerobic=50, long=60, tempo=65, interval=85, vo2max=90
- "targetKm": realistic distance based on ${profile.weeklyHours ?? 6}h/week at ~${avgSpeed} km/h avg
- "desc": 1–2 sentences with specific protocol (zones, durations, rep counts, HR targets)
- Apply polarized 80/20 principle: 80% Z1–Z2, 20% Z4–Z5
- Weeks 4, 8, 12: recovery weeks at 60% of surrounding volume
- Structure: weeks 1–6 base, 7–11 build, 12–14 peak, 15–16 taper
- Start volume conservatively based on detraining status, peak at week 11–12
- Each week's "targetKm" = sum of all days' targetKm
- "focus": one concise phrase describing the week's training emphasis

JSON SCHEMA:
{
  "weeks": [
    {
      "weekNumber": 1,
      "phase": "base",
      "isRecovery": false,
      "targetKm": 180,
      "focus": "Aerobic base, adapting to load",
      "days": [
        { "dayOfWeek": "Mo", "type": "rest",     "label": "Full rest",              "desc": "...", "intensity": 0,  "targetKm": 0  },
        { "dayOfWeek": "Tu", "type": "aerobic",  "label": "Z2 Endurance (50 km)",   "desc": "...", "intensity": 50, "targetKm": 50 },
        { "dayOfWeek": "We", "type": "recovery", "label": "Recovery ride (30 km)",  "desc": "...", "intensity": 15, "targetKm": 30 },
        { "dayOfWeek": "Th", "type": "tempo",    "label": "Sweet spot (45 km)",     "desc": "...", "intensity": 65, "targetKm": 45 },
        { "dayOfWeek": "Fr", "type": "rest",     "label": "Full rest",              "desc": "...", "intensity": 0,  "targetKm": 0  },
        { "dayOfWeek": "Sa", "type": "long",     "label": "Long ride (80 km)",      "desc": "...", "intensity": 60, "targetKm": 80 },
        { "dayOfWeek": "Su", "type": "recovery", "label": "Recovery ride (25 km)",  "desc": "...", "intensity": 15, "targetKm": 25 }
      ]
    }
  ]
}`;

    try {
      const res = await fetch('https://api.openai.com/v1/chat/completions', {
        method:  'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${OPENAI_KEY}` },
        body: JSON.stringify({
          model:           AI_PLAN_MODEL,
          response_format: { type: 'json_object' },
          max_tokens:      16000,
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user',   content: `Generate the 16-week ${sport} training plan. Start date: ${startLabel}. Weekly hours budget: ${profile.weeklyHours ?? 6}h/week.${profile.goalDate ? ` Peak for goal event on ${profile.goalDate}.` : ''} Week 1 day 1 must be ${startIso}.` },
          ],
        }),
      });
      if (!res.ok) throw new Error(`OpenAI error ${res.status}`);
      const data   = await res.json();
      const parsed = JSON.parse(data.choices?.[0]?.message?.content ?? '{}');

      const startD = new Date(startIso + 'T00:00:00Z');
      const weeks  = (parsed.weeks ?? []).map((week, wi) => {
        const weekMs = startD.getTime() + wi * 7 * 86400000;
        const days   = (week.days ?? []).map((d, di) => {
          const dayD   = new Date(weekMs + di * 86400000);
          const dateIso = dayD.toISOString().slice(0, 10);
          const isoDow  = (dayD.getUTCDay() + 6) % 7;
          return {
            ...d,
            day:    DAY_LABELS[isoDow] ?? d.dayOfWeek,
            date:   dateIso.slice(5).replace('-', '/'),
            dateIso,
            dow:    isoDow,
            color:  TYPE_COLOR[d.type]    ?? '#6b7280',
            intent: SESSION_INTENTS[d.type] ?? SESSION_INTENTS.aerobic,
          };
        });
        const targetKm = days.reduce((s, d) => s + (d.targetKm ?? 0), 0);
        return {
          weekIndex:  wi,
          phase:      week.phase      ?? 'base',
          isRecovery: week.isRecovery ?? false,
          targetKm:   week.targetKm   ?? targetKm,
          focus:      week.focus      ?? '',
          startDate:  new Date(weekMs).toISOString().slice(0, 10),
          endDate:    new Date(weekMs + 6 * 86400000).toISOString().slice(0, 10),
          days,
        };
      });

      const todayStr = localDateIso();
      const currentWeekIndex = Math.max(0, weeks.findIndex(w => w.startDate <= todayStr && w.endDate >= todayStr));
      const aiMc = { weeks, currentWeekIndex, meta: { totalWeeks: weeks.length, sport, goalDate: profile.goalDate, aiGenerated: true } };
      await coach.saveAIMesocycle(aiMc, histWorkouts);
      setSelectedWeekIndex(currentWeekIndex);
      setAiPlanState({ loading: false, error: '' });
    } catch (e) {
      setAiPlanState({ loading: false, error: e.message || 'AI plan generation failed' });
    }
  };

  const [confirm, setConfirm] = useState(null); // { title, body, confirmLabel, confirmColor, onConfirm }

  // Regenerate mesocycle with current start date selection
  const handleRegenerate = () => setConfirm({
    title:        'Regenerate full plan?',
    body:         'This will replace your entire mesocycle with a freshly generated plan. Any manual changes or AI plan will be lost.',
    confirmLabel: 'Regenerate',
    confirmColor: '#f97316',
    onConfirm:    () => coach?.regenerateMesocycle?.(histWorkouts, effectiveStartDate, null, { targetSport: planSport }),
  });

  const handleUpdateFuture = () => setConfirm({
    title:        'Update future weeks?',
    body:         `Weeks from today onwards will be recalculated based on your current fitness. Past weeks stay unchanged.${activeMesocycle?.meta?.aiGenerated ? ' The plan will remain marked as AI-generated.' : ''}`,
    confirmLabel: 'Update Future',
    confirmColor: '#60a5fa',
    onConfirm:    () => coach?.updateFutureMesocycle?.(histWorkouts, null, { targetSport: planSport }),
  });

  const isPaused = activeMesocycle?.status === 'paused';

  const handlePause = () => setConfirm({
    title:        'Pause training plan?',
    body:         'The plan will be paused. Your progress and history are preserved. Resume any time to continue.',
    confirmLabel: 'Pause',
    confirmColor: '#6b7280',
    onConfirm:    () => coach?.pauseMesocycle?.(),
  });

  const handleResume = () => setConfirm({
    title:        'Continue training plan?',
    body:         'The app will check if future weeks need to be adjusted based on the time elapsed. If so, it will recalculate from today — past weeks stay unchanged.',
    confirmLabel: 'Continue',
    confirmColor: '#4ade80',
    onConfirm:    () => coach?.resumeMesocycle?.(histWorkouts),
  });

  const handleGenerateAIPlan = () => setConfirm({
    title:        'Generate AI plan?',
    body:         'This will call gpt-4o to create a personalised 16-week plan based on your profile, fitness state, and recent training. It may take 20–40 seconds.',
    confirmLabel: '✦ Generate',
    confirmColor: '#a855f7',
    onConfirm:    generateAIPlan,
  });

  // ── Render ───────────────────────────────────────────────────────────────────
  const phaseColor = displayedWeek ? (PHASE_COLORS[displayedWeek.isRecovery ? 'recovery' : displayedWeek.phase] ?? '#60a5fa') : (activeMesocycle?.meta?.aiGenerated ? '#a855f7' : '#60a5fa');
  const phaseLabel = displayedWeek ? (displayedWeek.isRecovery ? 'Recovery Week' : (PHASE_LABELS[displayedWeek.phase] ?? displayedWeek.phase)) : '';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-4)' }}>

      {confirm && (
        <ConfirmModal
          title={confirm.title}
          body={confirm.body}
          confirmLabel={confirm.confirmLabel}
          confirmColor={confirm.confirmColor}
          onConfirm={confirm.onConfirm}
          onCancel={() => setConfirm(null)}
        />
      )}

      {/* Mesocycle header */}
      <div style={{
        background: `${phaseColor}10`, border: `1px solid ${phaseColor}30`,
        borderRadius: 'var(--r-md)', padding: 'var(--sp-3) var(--sp-4)',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 'var(--sp-2)' }}>
          <div>
            <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>
              MESOCYCLE · {activeMesocycle?.meta?.totalWeeks ?? '?'} WEEKS{activeMesocycle?.meta?.aiGenerated ? ' · AI' : ''}
            </div>
            <div style={{ fontSize: 13, color: phaseColor, fontWeight: 600 }}>
              Week {selectedWeekIndex + 1} of {activeMesocycle?.meta?.totalWeeks ?? '?'} · {phaseLabel}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
              {fmtDateDMY(displayedWeek?.startDate)} → {fmtDateDMY(displayedWeek?.endDate)}
              {activeMesocycle?.meta?.goalDate && ` · Goal: ${fmtDateDMY(activeMesocycle.meta.goalDate)}`}
            </div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 20, fontWeight: 600, color: phaseColor, fontFamily: 'var(--font-display)' }}>~{displayedWeek?.targetKm ?? 0} km</div>
            {weeklyCompliance && (
              <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                {weeklyCompliance.completed}/{weeklyCompliance.planned} sessions · {weeklyCompliance.completionRate}%
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Preview badge */}
      {isPreviewMode && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'rgba(96,165,250,0.08)', border: '1px solid rgba(96,165,250,0.25)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)' }}>
          <span style={{ fontSize: 11, color: '#60a5fa', fontFamily: 'var(--font-mono)' }}>
            Previewing week {selectedWeekIndex + 1} (starts {fmtDateDMY(displayedWeek?.startDate)})
          </span>
          <button
            onClick={() => setSelectedWeekIndex(currentWeekIdx)}
            style={{ background: 'rgba(96,165,250,0.15)', border: '1px solid rgba(96,165,250,0.35)', borderRadius: 'var(--r-sm)', padding: '3px 10px', fontSize: 11, color: '#60a5fa', cursor: 'pointer', fontFamily: 'var(--font-mono)' }}
          >← Current week</button>
        </div>
      )}

      {/* View toggle */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-3)', flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', gap: 6, flex: 1 }}>
          {[{ id: 'week', label: 'Week plan' }, { id: 'full', label: 'Full plan' }].map(opt => (
            <button key={opt.id} onClick={() => setViewMode(opt.id)} style={{
              flex: 1, background: viewMode === opt.id ? 'rgba(232,168,50,0.12)' : 'var(--bg-overlay)',
              border: `1px solid ${viewMode === opt.id ? 'rgba(232,168,50,0.45)' : 'var(--border-subtle)'}`,
              borderRadius: 'var(--r-md)', padding: 'var(--sp-2) var(--sp-3)',
              cursor: 'pointer', textAlign: 'center',
            }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: viewMode === opt.id ? 'var(--accent)' : 'var(--text-primary)' }}>{opt.label}</div>
            </button>
          ))}
        </div>
        <select
          value={planSport}
          onChange={e => {
            setHasManualPlanControls(true);
            setPlanSport(e.target.value);
          }}
          style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '6px 10px', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 12 }}
        >
          <option value="mixed">Mixed</option>
          <option value="running">Running</option>
          <option value="cycling">Cycling</option>
        </select>
      </div>

      {/* Start date + regenerate */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-2)', flexWrap: 'wrap' }}>
        <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', flexShrink: 0 }}>START</div>
        {[
          { id: 'auto',     label: 'Mon (auto)' },
          { id: 'today',    label: 'Today' },
          { id: 'tomorrow', label: 'Tomorrow' },
          { id: 'custom',   label: 'Pick date' },
        ].map(opt => (
          <button
            key={opt.id}
            onClick={() => {
              setHasManualPlanControls(true);
              setStartMode(opt.id);
            }}
            style={{
              background: startMode === opt.id ? 'rgba(232,168,50,0.12)' : 'var(--bg-overlay)',
              border: `1px solid ${startMode === opt.id ? 'rgba(232,168,50,0.45)' : 'var(--border-subtle)'}`,
              borderRadius: 'var(--r-sm)', padding: '4px 10px',
              color: startMode === opt.id ? 'var(--accent)' : 'var(--text-muted)',
              fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer',
            }}
          >{opt.label}</button>
        ))}
        {startMode === 'custom' && (
          <input
            type="date"
            value={customDate}
            onChange={e => {
              setHasManualPlanControls(true);
              setCustomDate(e.target.value);
            }}
            style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 8px', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 11 }}
          />
        )}
        <button
          onClick={isPaused ? handleResume : handlePause}
          style={{
            marginLeft: 'auto',
            background: isPaused ? 'rgba(74,222,128,0.12)' : 'var(--bg-overlay)',
            border: `1px solid ${isPaused ? 'rgba(74,222,128,0.4)' : 'var(--border-subtle)'}`,
            borderRadius: 'var(--r-sm)', padding: '4px 10px',
            color: isPaused ? '#4ade80' : 'var(--text-muted)',
            fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer',
          }}
        >{isPaused ? '▶ Continue plan' : '⏸ Pause plan'}</button>
        <button
          onClick={handleUpdateFuture}
          disabled={isPaused}
          style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 10px', color: isPaused ? 'var(--text-dim)' : 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: 11, cursor: isPaused ? 'default' : 'pointer' }}
        >Update Future</button>
        <button
          onClick={handleRegenerate}
          style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 10px', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer' }}
        >Regenerate</button>
        <button
          onClick={handleGenerateAIPlan}
          disabled={aiPlanState.loading}
          style={{ background: aiPlanState.loading ? 'rgba(168,85,247,0.06)' : 'rgba(168,85,247,0.12)', border: '1px solid rgba(168,85,247,0.4)', borderRadius: 'var(--r-sm)', padding: '4px 10px', color: aiPlanState.loading ? 'rgba(168,85,247,0.5)' : '#a855f7', fontFamily: 'var(--font-mono)', fontSize: 11, cursor: aiPlanState.loading ? 'default' : 'pointer' }}
        >{aiPlanState.loading ? 'AI generating…' : '✦ AI Plan'}</button>
      </div>

      {/* Paused banner */}
      {isPaused && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'rgba(107,114,128,0.08)', border: '1px solid rgba(107,114,128,0.3)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)' }}>
          <span style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
            ⏸ Plan paused{activeMesocycle?.pausedAt ? ` · since ${activeMesocycle.pausedAt.slice(0, 10)}` : ''}
          </span>
          <button onClick={handleResume}
            style={{ background: 'rgba(74,222,128,0.12)', border: '1px solid rgba(74,222,128,0.35)', borderRadius: 'var(--r-sm)', padding: '3px 10px', fontSize: 11, color: '#4ade80', cursor: 'pointer', fontFamily: 'var(--font-mono)' }}>
            ▶ Continue plan
          </button>
        </div>
      )}

      {/* AI plan active banner */}
      {activeMesocycle?.meta?.aiGenerated && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'rgba(168,85,247,0.08)', border: '1px solid rgba(168,85,247,0.3)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)' }}>
          <span style={{ fontSize: 11, color: '#a855f7', fontFamily: 'var(--font-mono)' }}>✦ AI-generated 16-week plan active</span>
          <button onClick={handleRegenerate}
            style={{ background: 'rgba(168,85,247,0.15)', border: '1px solid rgba(168,85,247,0.35)', borderRadius: 'var(--r-sm)', padding: '3px 10px', fontSize: 11, color: '#a855f7', cursor: 'pointer', fontFamily: 'var(--font-mono)' }}>
            Revert to template
          </button>
        </div>
      )}

      {/* AI plan error */}
      {aiPlanState.error && (
        <div style={{ fontSize: 11, color: '#ef4444', fontFamily: 'var(--font-mono)', background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)' }}>
          {aiPlanState.error}
        </div>
      )}

      {/* ── Full plan view ─────────────────────────────────────────────────── */}
      {viewMode === 'full' && (
        <div style={{ overflowX: 'auto', paddingBottom: 'var(--sp-2)' }}>
          <div style={{ display: 'flex', gap: 'var(--sp-2)', minWidth: 'max-content' }}>
            {(activeMesocycle?.weeks ?? []).map((week, i) => (
              <WeekCard
                key={week.weekIndex}
                week={week}
                isCurrent={i === currentWeekIdx}
                isSelected={i === selectedWeekIndex}
                onClick={() => { setSelectedWeekIndex(i); setViewMode('week'); }}
              />
            ))}
          </div>
        </div>
      )}

      {/* ── Week view ──────────────────────────────────────────────────────── */}
      {viewMode === 'week' && (
        <>
          {/* Week navigation */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-2)' }}>
            <button onClick={() => setSelectedWeekIndex(i => Math.max(0, i - 1))} disabled={selectedWeekIndex === 0}
              style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 12px', color: selectedWeekIndex === 0 ? 'var(--text-dim)' : 'var(--text-secondary)', cursor: selectedWeekIndex === 0 ? 'default' : 'pointer', fontSize: 16 }}>‹</button>
            <div style={{ flex: 1, textAlign: 'center', fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
              Week {selectedWeekIndex + 1} / {activeMesocycle?.weeks?.length ?? '?'}
            </div>
            <button onClick={() => setSelectedWeekIndex(i => Math.min((activeMesocycle?.weeks?.length ?? 1) - 1, i + 1))} disabled={selectedWeekIndex >= (activeMesocycle?.weeks?.length ?? 1) - 1}
              style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 12px', color: selectedWeekIndex >= (activeMesocycle?.weeks?.length ?? 1) - 1 ? 'var(--text-dim)' : 'var(--text-secondary)', cursor: selectedWeekIndex >= (activeMesocycle?.weeks?.length ?? 1) - 1 ? 'default' : 'pointer', fontSize: 16 }}>›</button>
          </div>

          {/* Day cards */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-2)' }}>
            {plan.map((day, i) => (
              <DayCard
                key={day.dateIso ?? day.day}
                day={day}
                weather={weather.days[Math.round((new Date(day.dateIso) - new Date(todayIso)) / 86400000)]}
                index={i}
                revealed={revealed}
                compliance={complianceByDate[day.dateIso]}
              />
            ))}
          </div>

          {/* Intensity chart */}
          <Card style={{ padding: 'var(--sp-4) var(--sp-3) var(--sp-3)' }}>
            <CardLabel>Daily intensity</CardLabel>
            <ResponsiveContainer width="100%" height={110}>
              <BarChart data={plan} margin={{ top: 0, right: 4, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" />
                <XAxis dataKey="day" tick={{ fill: '#3a3d4e', fontSize: 11, fontFamily: 'var(--font-mono)' }} axisLine={false} tickLine={false} />
                <YAxis domain={[0, 100]} tick={{ fill: '#3a3d4e', fontSize: 10 }} axisLine={false} tickLine={false} width={24} />
                <Tooltip
                  contentStyle={{ background: 'var(--bg-raised)', border: '1px solid var(--border-mid)', borderRadius: 8, fontSize: 12, fontFamily: 'var(--font-mono)', color: 'var(--text-primary)' }}
                  formatter={(v, _, p) => [`${v}%`, p.payload.label]}
                />
                <Bar dataKey="intensity" radius={[3, 3, 0, 0]}>
                  {plan.map((d, i) => <Cell key={i} fill={d.current ? '#e8a832' : d.color} opacity={d.current ? 1 : 0.75} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </Card>

          {/* Weekly goals */}
          <Card>
            <CardLabel>Weekly goals</CardLabel>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--sp-3)' }}>
              {[
                { icon: '📏', label: 'Target volume',   value: `~${displayedWeek?.targetKm ?? 0} km` },
                { icon: '💚', label: 'Z1-Z2 share',      value: displayedWeek?.isRecovery ? '≥ 90%' : '≥ 75%' },
                { icon: '⚡', label: 'Intense sessions', value: displayedWeek?.isRecovery ? '0' : (displayedWeek?.phase === 'build' || displayedWeek?.phase === 'peak') ? '2' : '1' },
                { icon: '😴', label: 'Rest days',        value: displayedWeek?.isRecovery ? '2–3' : '1–2' },
              ].map(g => (
                <div key={g.label} style={{ background: 'var(--bg-raised)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-md)', padding: 'var(--sp-3)', display: 'flex', gap: 'var(--sp-3)', alignItems: 'center' }}>
                  <span style={{ fontSize: 20 }}>{g.icon}</span>
                  <div>
                    <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{g.label}</div>
                    <div style={{ fontSize: 13, color: 'var(--text-primary)', fontWeight: 600 }}>{g.value}</div>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </>
      )}

      {/* Weather card */}
      <Card style={{ padding: 'var(--sp-4) var(--sp-3)' }}>
        <CardLabel>Weather (OpenWeather)</CardLabel>
        <div style={{ display: 'flex', gap: 'var(--sp-2)', marginBottom: 'var(--sp-3)', flexWrap: 'wrap' }}>
          {[{ id: 'workout', label: 'By workout GPS' }, { id: 'city', label: 'By city' }].map(opt => (
            <button key={opt.id} onClick={() => setWeatherSource(opt.id)} style={{
              background:   weatherSource === opt.id ? 'rgba(232,168,50,0.12)' : 'var(--bg-overlay)',
              border:       `1px solid ${weatherSource === opt.id ? 'rgba(232,168,50,0.45)' : 'var(--border-subtle)'}`,
              borderRadius: 'var(--r-sm)', padding: '4px 10px', fontSize: 11,
              color:        weatherSource === opt.id ? 'var(--accent)' : 'var(--text-secondary)',
              fontFamily:   'var(--font-mono)', cursor: 'pointer',
            }}>{opt.label}</button>
          ))}
        </div>
        {weatherSource === 'city' && (
          <div style={{ marginBottom: 'var(--sp-3)' }}>
            <input
              value={cityInput}
              onChange={e => { setWeatherSource('city'); setCityInput(e.target.value); }}
              placeholder="City name…"
              style={{ width: '100%', boxSizing: 'border-box', background: 'var(--bg-raised)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '5px 10px', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 12 }}
            />
          </div>
        )}
        {weather.loading && <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>Loading weather…</div>}
        {weather.error  && <div style={{ fontSize: 11, color: '#ef4444', fontFamily: 'var(--font-mono)' }}>{weather.error}</div>}
        {!weather.loading && weather.location && <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 'var(--sp-2)' }}>📍 {weather.location}</div>}
        {!weather.loading && weather.days.length > 0 && (
          <div style={{ display: 'flex', gap: 'var(--sp-2)', overflowX: 'auto', paddingBottom: 4 }}>
            {weather.days.map((d, i) => (
              <div key={i} style={{ minWidth: 72, background: 'var(--bg-raised)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2)', flexShrink: 0 }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>{i === 0 ? 'Today' : i === 1 ? 'Tomorrow' : `Day ${i + 1}`}</div>
                <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{d.tempC}°C · {d.weatherLabel || '—'}</div>
                <div style={{ fontSize: 11, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' }}>Wind: {d.windKmh} km/h, {d.windDir}</div>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
