/**
 * PlanTab.jsx — Multi-week mesocycle plan with week/full views.
 * Props: { workout, history, coach }
 * Data source: coach.mesocycle (generated by useCoachState + trainingEngine)
 * PlanTab never calls generateTrainingPlan directly — it reads mesocycle.weeks[selectedWeekIndex].
 */
import { useState, useEffect, useMemo } from 'react';
import { BarChart, Bar, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { generateMesocycle, PHASE_COLORS, PHASE_LABELS } from '../../core/trainingEngine.js';
import { Card, CardLabel } from './OverviewTab.jsx';

const OPENWEATHER_API_KEY = import.meta.env.VITE_OPENWEATHER_API_KEY ?? '';

function windDirection(deg) {
  if (deg == null || Number.isNaN(deg)) return '—';
  const dirs = ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NNW'];
  const idx = Math.round((((deg % 360) + 360) % 360) / 22.5) % 16;
  return dirs[idx];
}

function extractWorkoutCoords(workout) {
  const points = workout?.timeSeries ?? [];
  const point = points.find(p => Number.isFinite(p?.lat) && Number.isFinite(p?.lon));
  return point ? { lat: point.lat, lon: point.lon } : null;
}

function pickDailyForecastFrom3h(list = [], dayIndex = 0) {
  if (!list.length) return null;
  const target = new Date();
  target.setHours(12, 0, 0, 0);
  target.setDate(target.getDate() + dayIndex);
  const targetMs = target.getTime();
  const sameDay = list.filter(item => {
    const dt = new Date((item.dt ?? 0) * 1000);
    return dt.getFullYear() === target.getFullYear() &&
           dt.getMonth()    === target.getMonth()    &&
           dt.getDate()     === target.getDate();
  });
  if (!sameDay.length) return null;
  let best = sameDay[0];
  let bestDiff = Math.abs(((best.dt ?? 0) * 1000) - targetMs);
  for (let i = 1; i < sameDay.length; i++) {
    const diff = Math.abs(((sameDay[i].dt ?? 0) * 1000) - targetMs);
    if (diff < bestDiff) { best = sameDay[i]; bestDiff = diff; }
  }
  const windMs = Number(best?.wind?.speed ?? 0);
  return {
    tempC:        Math.round(best?.main?.temp ?? 0),
    windMs:       parseFloat(windMs.toFixed(1)),
    windKmh:      Math.round(windMs * 3.6),
    windDeg:      best?.wind?.deg ?? null,
    windDir:      windDirection(best?.wind?.deg),
    weatherLabel: best?.weather?.[0]?.main ?? '',
  };
}

// ── Phase context banner ──────────────────────────────────────────────────────

export function PlanContextBanner({ meta, mesocycleMeta }) {
  const dt    = meta.detraining;
  const load  = meta.load;
  const phase = meta.phase;

  const phaseColor = {
    full_restart: '#ef4444', base_rebuild: '#f97316', significant: '#fbbf24',
    moderate: '#a3e635', slight: '#60a5fa', overreached: '#ef4444',
    active: '#4ade80', too_easy: '#a78bfa',
  }[phase] ?? '#6b7280';

  const tsbColor = load.tsb > 5 ? '#4ade80' : load.tsb < -15 ? '#ef4444' : '#fbbf24';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-3)' }}>
      <div style={{
        background: `${phaseColor}10`, border: `1px solid ${phaseColor}30`,
        borderRadius: 'var(--r-md)', padding: 'var(--sp-3) var(--sp-4)',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
      }}>
        <div>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>TRAINING PHASE</div>
          <div style={{ fontSize: 13, color: phaseColor, fontWeight: 600 }}>{dt.label}</div>
          {dt.daysSince < 999 && (
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
              Last workout: {dt.daysSince === 0 ? 'today' : `${dt.daysSince} days ago`}
            </div>
          )}
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ fontSize: 9, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 4 }}>WEEK VOLUME</div>
          <div style={{ fontSize: 20, fontWeight: 600, color: phaseColor, fontFamily: 'var(--font-display)' }}>~{meta.targetWeekKm} km</div>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
            base {meta.baseKm} km × {Math.round(100 / meta.baseKm * meta.targetWeekKm)}%
          </div>
        </div>
      </div>
      {(load.ctl > 0 || load.atl > 0) && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 'var(--sp-2)' }}>
          {[
            { label: 'CTL (fitness)',    value: load.ctl.toFixed(1), color: '#60a5fa', sub: 'avg TE/42 days' },
            { label: 'ATL (load)',       value: load.atl.toFixed(1), color: '#f97316', sub: 'avg TE/7 days'  },
            { label: 'TSB (freshness)', value: (load.tsb > 0 ? '+' : '') + load.tsb.toFixed(1), color: tsbColor, sub: load.tsb > 5 ? 'fresh' : load.tsb < -15 ? 'fatigue' : 'neutral' },
          ].map(item => (
            <div key={item.label} style={{
              background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)',
              borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)',
            }}>
              <div style={{ fontSize: 9, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>{item.label}</div>
              <div style={{ fontSize: 18, fontWeight: 600, color: item.color, fontFamily: 'var(--font-display)', lineHeight: 1 }}>{item.value}</div>
              <div style={{ fontSize: 9, color: 'var(--text-dim)', marginTop: 2 }}>{item.sub}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Day card ─────────────────────────────────────────────────────────────────

function DayCard({ day, weather, index, revealed, compliance }) {
  const highlight = day.current;
  const compBadge = compliance ? {
    nailed_it:  { color: '#4ade80', label: 'Nailed it' },
    close:      { color: '#fbbf24', label: 'Close' },
    off_target: { color: '#f97316', label: 'Off target' },
    skipped:    { color: '#ef4444', label: 'Skipped' },
  }[compliance.verdict] : null;

  return (
    <div style={{
      background:    highlight ? `${day.color}0d` : 'var(--bg-overlay)',
      border:        `1px solid ${highlight ? `${day.color}35` : 'var(--border-subtle)'}`,
      borderRadius:  'var(--r-md)', padding: 'var(--sp-3) var(--sp-4)',
      display: 'flex', flexDirection: 'column', gap: 'var(--sp-2)',
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div style={{ display: 'flex', gap: 'var(--sp-3)', alignItems: 'flex-start', flex: 1 }}>
          <div style={{ minWidth: 28 }}>
            <div style={{ fontSize: 11, fontWeight: 600, color: highlight ? day.color : 'var(--text-secondary)', fontFamily: 'var(--font-mono)', lineHeight: 1.2 }}>{day.day}</div>
            {day.date && <div style={{ fontSize: 9, color: 'var(--text-dim)', fontFamily: 'var(--font-mono)' }}>{day.date}</div>}
          </div>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap' }}>
              <span style={{ fontSize: 13, color: highlight ? 'var(--text-primary)' : 'var(--text-secondary)' }}>{day.label}</span>
              {day.current && (
                <span style={{ fontSize: 9, color: day.color, fontFamily: 'var(--font-mono)', background: `${day.color}18`, border: `1px solid ${day.color}40`, borderRadius: 4, padding: '2px 6px', letterSpacing: '0.06em' }}>TODAY</span>
              )}
              {compBadge && (
                <span style={{ fontSize: 9, color: compBadge.color, fontFamily: 'var(--font-mono)', background: `${compBadge.color}18`, border: `1px solid ${compBadge.color}40`, borderRadius: 4, padding: '2px 6px' }}>{compBadge.label}</span>
              )}
            </div>
            {day.desc && <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 2 }}>{day.desc}</div>}
            {weather && (
              <div style={{ fontSize: 10, color: 'var(--text-secondary)', marginTop: 4, fontFamily: 'var(--font-mono)' }}>
                {weather.tempC}°C · wind {weather.windKmh} km/h {weather.windDir}
              </div>
            )}
          </div>
        </div>
        <div style={{ textAlign: 'right', flexShrink: 0 }}>
          <div style={{ fontSize: 10, color: day.color, fontFamily: 'var(--font-mono)', textTransform: 'uppercase' }}>{day.type}</div>
          {day.targetKm > 0 && <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>~{day.targetKm} km</div>}
          {compBadge && compliance?.details?.distanceDelta && (
            <div style={{ fontSize: 9, color: 'var(--text-dim)', fontFamily: 'var(--font-mono)' }}>
              {compliance.details.distanceDelta.actual?.toFixed(1)} km actual
            </div>
          )}
        </div>
      </div>
      <div style={{ height: 4, background: 'var(--bg-raised)', borderRadius: 2, overflow: 'hidden' }}>
        <div style={{
          height: '100%', width: revealed ? `${day.intensity}%` : '0%',
          background: highlight ? `linear-gradient(90deg,${day.color}88,${day.color})` : day.color,
          borderRadius: 2, transition: revealed ? 'width 0.6s var(--ease-snappy)' : 'none',
          transitionDelay: revealed ? `${index * 60 + 200}ms` : '0ms',
          boxShadow: highlight ? `0 0 6px ${day.color}55` : 'none',
        }} />
      </div>
    </div>
  );
}

// ── Week card (full plan view) ────────────────────────────────────────────────

function WeekCard({ week, isCurrent, isSelected, onClick }) {
  const phase = week.isRecovery ? 'recovery' : week.phase;
  const phaseColor = PHASE_COLORS[phase] ?? '#6b7280';
  const phaseLabel = week.isRecovery ? 'Recovery' : (PHASE_LABELS[phase] ?? phase);

  const sessionIcons = week.days.map(d => ({
    rest:     '—', recovery: '◦', aerobic: '●', tempo: '▲',
    interval: '★', long: '◉', test: '◈',
  }[d.type] ?? '●'));

  return (
    <div
      onClick={onClick}
      style={{
        background:   isSelected ? `${phaseColor}15` : 'var(--bg-overlay)',
        border:       `1px solid ${isCurrent ? phaseColor : isSelected ? `${phaseColor}60` : 'var(--border-subtle)'}`,
        borderRadius: 'var(--r-md)', padding: 'var(--sp-3)',
        cursor: 'pointer', minWidth: 120, flexShrink: 0,
        transition: 'all var(--t-base) var(--ease-snappy)',
        position: 'relative',
      }}
    >
      {isCurrent && (
        <div style={{ position: 'absolute', top: -8, left: '50%', transform: 'translateX(-50%)', fontSize: 9, fontFamily: 'var(--font-mono)', color: phaseColor, background: 'var(--bg-base)', padding: '1px 6px', border: `1px solid ${phaseColor}`, borderRadius: 4 }}>NOW</div>
      )}
      <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>Week {week.weekIndex + 1}</div>
      <div style={{ fontSize: 11, color: phaseColor, fontWeight: 600, marginBottom: 4 }}>{phaseLabel}</div>
      <div style={{ fontSize: 12, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', marginBottom: 6 }}>{week.targetKm} km</div>
      <div style={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
        {sessionIcons.map((icon, i) => (
          <span key={i} style={{ fontSize: 8, color: week.days[i] ? (PHASE_COLORS[week.days[i].type] ?? phaseColor) : 'var(--text-dim)' }}>{icon}</span>
        ))}
      </div>
    </div>
  );
}

// ── Main PlanTab ──────────────────────────────────────────────────────────────

function todayIsoStr() { return new Date().toISOString().slice(0, 10); }
function tomorrowIsoStr() {
  const d = new Date(); d.setDate(d.getDate() + 1);
  return d.toISOString().slice(0, 10);
}

export function PlanTab({ workout: w, history, coach }) {
  const [viewMode, setViewMode] = useState('week');
  const [planSport, setPlanSport] = useState(() => {
    const t = coach?.profile?.targetSport;
    return (t === 'running' || t === 'cycling' || t === 'mixed') ? t : 'mixed';
  });
  // 'auto' = current Monday (legacy default), 'today', 'tomorrow', 'custom'
  const [startMode, setStartMode] = useState('auto');
  const [customDate, setCustomDate] = useState(() => todayIsoStr());

  const effectiveStartDate = useMemo(() => {
    if (startMode === 'today')    return todayIsoStr();
    if (startMode === 'tomorrow') return tomorrowIsoStr();
    if (startMode === 'custom')   return customDate;
    return null; // auto → Monday snap inside generateMesocycle
  }, [startMode, customDate]);

  const histWorkouts = history?.history ?? [];

  // Get or generate mesocycle
  const mesocycle = useMemo(() => {
    if (coach?.mesocycle?.weeks?.length && startMode === 'auto') return coach.mesocycle;
    // Fallback or custom start: generate on the fly
    const profile = coach?.profile ?? {};
    const sportProfile = { ...profile, targetSport: planSport !== 'mixed' ? planSport : (profile.targetSport ?? 'running') };
    return generateMesocycle(sportProfile, histWorkouts, effectiveStartDate);
  }, [coach?.mesocycle, coach?.profile, histWorkouts, planSport, effectiveStartDate, startMode]);

  const [selectedWeekIndex, setSelectedWeekIndex] = useState(() => mesocycle?.currentWeekIndex ?? 0);

  // Keep selectedWeekIndex in sync when mesocycle changes
  useEffect(() => {
    if (mesocycle?.currentWeekIndex != null) {
      setSelectedWeekIndex(mesocycle.currentWeekIndex);
    }
  }, [mesocycle?.currentWeekIndex]);

  const displayedWeek  = mesocycle?.weeks?.[selectedWeekIndex] ?? null;
  const currentWeekIdx = mesocycle?.currentWeekIndex ?? 0;
  const isPreviewMode  = selectedWeekIndex !== currentWeekIdx;
  const todayIso       = new Date().toISOString().slice(0, 10);

  const plan = useMemo(() => {
    if (!displayedWeek) return [];
    return displayedWeek.days.map((d, i) => ({
      ...d,
      current: d.dateIso === todayIso,
    }));
  }, [displayedWeek, todayIso]);

  // Compliance per day (from history)
  const complianceByDate = useMemo(() => {
    const map = {};
    for (const w of histWorkouts) {
      if (w.complianceResult) map[w.date] = w.complianceResult;
    }
    return map;
  }, [histWorkouts]);

  // Weekly compliance summary
  const weeklyCompliance = useMemo(() => {
    if (!displayedWeek) return null;
    const plannedDays = displayedWeek.days.filter(d => d.type !== 'rest');
    const completed = plannedDays.filter(d => histWorkouts.some(w => w.date === d.dateIso));
    if (!plannedDays.length) return null;
    return {
      completionRate: Math.round((completed.length / plannedDays.length) * 100),
      completed: completed.length,
      planned: plannedDays.length,
    };
  }, [displayedWeek, histWorkouts]);

  const coords = extractWorkoutCoords(w);

  // ── Weather ─────────────────────────────────────────────────────────────────
  const [weatherSource, setWeatherSource] = useState('workout');
  const [cityInput, setCityInput]         = useState(() => { try { return localStorage.getItem('plan_weather_city') || ''; } catch { return ''; } });
  const [cityQuery, setCityQuery]         = useState(cityInput);
  const [weather, setWeather]             = useState({ loading: false, error: '', days: [], location: '' });

  useEffect(() => {
    if (!OPENWEATHER_API_KEY) return;
    const ctrl = new AbortController();
    async function fetchForecast() {
      setWeather(prev => ({ ...prev, loading: true, error: '' }));
      try {
        let lat, lon;
        if (weatherSource === 'workout' && coords) {
          lat = coords.lat; lon = coords.lon;
        } else if (weatherSource === 'city' && cityQuery.trim()) {
          const geoRes  = await fetch(`https://api.openweathermap.org/geo/1.0/direct?q=${encodeURIComponent(cityQuery.trim())}&limit=1&appid=${OPENWEATHER_API_KEY}`, { signal: ctrl.signal });
          const geoData = await geoRes.json();
          if (!geoData?.length) throw new Error('City not found');
          lat = geoData[0].lat; lon = geoData[0].lon;
        } else {
          setWeather({ loading: false, error: '', days: [], location: '' });
          return;
        }
        const res  = await fetch(`https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&units=metric&appid=${OPENWEATHER_API_KEY}`, { signal: ctrl.signal });
        const data = await res.json();
        const list = Array.isArray(data?.list) ? data.list : [];
        const days = Array.from({ length: 7 }, (_, i) => pickDailyForecastFrom3h(list, i)).filter(Boolean);
        setWeather({ loading: false, error: '', days, location: data?.city?.name || (weatherSource === 'city' ? cityQuery.trim() : 'Workout location') });
      } catch (e) {
        if (e.name === 'AbortError') return;
        setWeather({ loading: false, error: e.message || 'Weather load error', days: [], location: '' });
      }
    }
    fetchForecast();
    return () => ctrl.abort();
  }, [coords?.lat, coords?.lon, weatherSource, cityQuery]);

  const applyCity = () => {
    const next = cityInput.trim();
    if (!next) return;
    setWeatherSource('city');
    setCityQuery(next);
    try { localStorage.setItem('plan_weather_city', next); } catch {}
  };

  const [revealed, setRevealed] = useState(false);
  useEffect(() => { const t = setTimeout(() => setRevealed(true), 80); return () => clearTimeout(t); }, []);

  // Regenerate mesocycle with current start date selection
  const handleRegenerate = () => {
    if (coach?.regenerateMesocycle) {
      coach.regenerateMesocycle(histWorkouts, effectiveStartDate);
    }
  };

  // ── Render ───────────────────────────────────────────────────────────────────
  const phaseColor = displayedWeek ? PHASE_COLORS[displayedWeek.isRecovery ? 'recovery' : displayedWeek.phase] ?? '#60a5fa' : '#60a5fa';
  const phaseLabel = displayedWeek ? (displayedWeek.isRecovery ? 'Recovery Week' : (PHASE_LABELS[displayedWeek.phase] ?? displayedWeek.phase)) : '';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-4)' }}>

      {/* Mesocycle header */}
      <div style={{
        background: `${phaseColor}10`, border: `1px solid ${phaseColor}30`,
        borderRadius: 'var(--r-md)', padding: 'var(--sp-3) var(--sp-4)',
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 'var(--sp-2)' }}>
          <div>
            <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>
              MESOCYCLE · {mesocycle?.meta?.totalWeeks ?? '?'} WEEKS
            </div>
            <div style={{ fontSize: 13, color: phaseColor, fontWeight: 600 }}>
              Week {selectedWeekIndex + 1} of {mesocycle?.meta?.totalWeeks ?? '?'} · {phaseLabel}
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
              {displayedWeek?.startDate} → {displayedWeek?.endDate}
              {mesocycle?.meta?.goalDate && ` · Goal: ${mesocycle.meta.goalDate}`}
            </div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 20, fontWeight: 600, color: phaseColor, fontFamily: 'var(--font-display)' }}>~{displayedWeek?.targetKm ?? 0} km</div>
            {weeklyCompliance && (
              <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
                {weeklyCompliance.completed}/{weeklyCompliance.planned} sessions · {weeklyCompliance.completionRate}%
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Preview badge */}
      {isPreviewMode && (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'rgba(96,165,250,0.08)', border: '1px solid rgba(96,165,250,0.25)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2) var(--sp-3)' }}>
          <span style={{ fontSize: 11, color: '#60a5fa', fontFamily: 'var(--font-mono)' }}>
            Previewing week {selectedWeekIndex + 1} (starts {displayedWeek?.startDate})
          </span>
          <button
            onClick={() => setSelectedWeekIndex(currentWeekIdx)}
            style={{ background: 'rgba(96,165,250,0.15)', border: '1px solid rgba(96,165,250,0.35)', borderRadius: 'var(--r-sm)', padding: '3px 10px', fontSize: 11, color: '#60a5fa', cursor: 'pointer', fontFamily: 'var(--font-mono)' }}
          >← Current week</button>
        </div>
      )}

      {/* View toggle */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-3)', flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', gap: 6, flex: 1 }}>
          {[{ id: 'week', label: 'Week plan' }, { id: 'full', label: 'Full plan' }].map(opt => (
            <button key={opt.id} onClick={() => setViewMode(opt.id)} style={{
              flex: 1, background: viewMode === opt.id ? 'rgba(232,168,50,0.12)' : 'var(--bg-overlay)',
              border: `1px solid ${viewMode === opt.id ? 'rgba(232,168,50,0.45)' : 'var(--border-subtle)'}`,
              borderRadius: 'var(--r-md)', padding: 'var(--sp-2) var(--sp-3)',
              cursor: 'pointer', textAlign: 'center',
            }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: viewMode === opt.id ? 'var(--accent)' : 'var(--text-primary)' }}>{opt.label}</div>
            </button>
          ))}
        </div>
        <select
          value={planSport}
          onChange={e => setPlanSport(e.target.value)}
          style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '6px 10px', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 12 }}
        >
          <option value="mixed">Mixed</option>
          <option value="running">Running</option>
          <option value="cycling">Cycling</option>
        </select>
      </div>

      {/* Start date + regenerate */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-2)', flexWrap: 'wrap' }}>
        <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', flexShrink: 0 }}>START</div>
        {[
          { id: 'auto',     label: 'Mon (auto)' },
          { id: 'today',    label: 'Today' },
          { id: 'tomorrow', label: 'Tomorrow' },
          { id: 'custom',   label: 'Pick date' },
        ].map(opt => (
          <button
            key={opt.id}
            onClick={() => setStartMode(opt.id)}
            style={{
              background: startMode === opt.id ? 'rgba(232,168,50,0.12)' : 'var(--bg-overlay)',
              border: `1px solid ${startMode === opt.id ? 'rgba(232,168,50,0.45)' : 'var(--border-subtle)'}`,
              borderRadius: 'var(--r-sm)', padding: '4px 10px',
              color: startMode === opt.id ? 'var(--accent)' : 'var(--text-muted)',
              fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer',
            }}
          >{opt.label}</button>
        ))}
        {startMode === 'custom' && (
          <input
            type="date"
            value={customDate}
            onChange={e => setCustomDate(e.target.value)}
            style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 8px', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 11 }}
          />
        )}
        <button
          onClick={handleRegenerate}
          style={{ marginLeft: 'auto', background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 10px', color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer' }}
        >Regenerate</button>
      </div>

      {/* ── Full plan view ─────────────────────────────────────────────────── */}
      {viewMode === 'full' && (
        <div style={{ overflowX: 'auto', paddingBottom: 'var(--sp-2)' }}>
          <div style={{ display: 'flex', gap: 'var(--sp-2)', minWidth: 'max-content' }}>
            {(mesocycle?.weeks ?? []).map((week, i) => (
              <WeekCard
                key={week.weekIndex}
                week={week}
                isCurrent={i === currentWeekIdx}
                isSelected={i === selectedWeekIndex}
                onClick={() => { setSelectedWeekIndex(i); setViewMode('week'); }}
              />
            ))}
          </div>
        </div>
      )}

      {/* ── Week view ──────────────────────────────────────────────────────── */}
      {viewMode === 'week' && (
        <>
          {/* Week navigation */}
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--sp-2)' }}>
            <button onClick={() => setSelectedWeekIndex(i => Math.max(0, i - 1))} disabled={selectedWeekIndex === 0}
              style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 12px', color: selectedWeekIndex === 0 ? 'var(--text-dim)' : 'var(--text-secondary)', cursor: selectedWeekIndex === 0 ? 'default' : 'pointer', fontSize: 16 }}>‹</button>
            <div style={{ flex: 1, textAlign: 'center', fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>
              Week {selectedWeekIndex + 1} / {mesocycle?.weeks?.length ?? '?'}
            </div>
            <button onClick={() => setSelectedWeekIndex(i => Math.min((mesocycle?.weeks?.length ?? 1) - 1, i + 1))} disabled={selectedWeekIndex >= (mesocycle?.weeks?.length ?? 1) - 1}
              style={{ background: 'var(--bg-overlay)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '4px 12px', color: selectedWeekIndex >= (mesocycle?.weeks?.length ?? 1) - 1 ? 'var(--text-dim)' : 'var(--text-secondary)', cursor: selectedWeekIndex >= (mesocycle?.weeks?.length ?? 1) - 1 ? 'default' : 'pointer', fontSize: 16 }}>›</button>
          </div>

          {/* Day cards */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--sp-2)' }}>
            {plan.map((day, i) => (
              <DayCard
                key={day.dateIso ?? day.day}
                day={day}
                weather={weather.days[Math.round((new Date(day.dateIso) - new Date(todayIso)) / 86400000)]}
                index={i}
                revealed={revealed}
                compliance={complianceByDate[day.dateIso]}
              />
            ))}
          </div>

          {/* Intensity chart */}
          <Card style={{ padding: 'var(--sp-4) var(--sp-3) var(--sp-3)' }}>
            <CardLabel>Daily intensity</CardLabel>
            <ResponsiveContainer width="100%" height={110}>
              <BarChart data={plan} margin={{ top: 0, right: 4, left: 0, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" />
                <XAxis dataKey="day" tick={{ fill: '#3a3d4e', fontSize: 11, fontFamily: 'var(--font-mono)' }} axisLine={false} tickLine={false} />
                <YAxis domain={[0, 100]} tick={{ fill: '#3a3d4e', fontSize: 10 }} axisLine={false} tickLine={false} width={24} />
                <Tooltip
                  contentStyle={{ background: 'var(--bg-raised)', border: '1px solid var(--border-mid)', borderRadius: 8, fontSize: 12, fontFamily: 'var(--font-mono)', color: 'var(--text-primary)' }}
                  formatter={(v, _, p) => [`${v}%`, p.payload.label]}
                />
                <Bar dataKey="intensity" radius={[3, 3, 0, 0]}>
                  {plan.map((d, i) => <Cell key={i} fill={d.current ? '#e8a832' : d.color} opacity={d.current ? 1 : 0.75} />)}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </Card>

          {/* Weekly goals */}
          <Card>
            <CardLabel>Weekly goals</CardLabel>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--sp-3)' }}>
              {[
                { icon: '📏', label: 'Target volume',   value: `~${displayedWeek?.targetKm ?? 0} km` },
                { icon: '💚', label: 'Z1-Z2 share',      value: displayedWeek?.isRecovery ? '≥ 90%' : '≥ 75%' },
                { icon: '⚡', label: 'Intense sessions', value: displayedWeek?.isRecovery ? '0' : (displayedWeek?.phase === 'build' || displayedWeek?.phase === 'peak') ? '2' : '1' },
                { icon: '😴', label: 'Rest days',        value: displayedWeek?.isRecovery ? '2–3' : '1–2' },
              ].map(g => (
                <div key={g.label} style={{ background: 'var(--bg-raised)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-md)', padding: 'var(--sp-3)', display: 'flex', gap: 'var(--sp-3)', alignItems: 'center' }}>
                  <span style={{ fontSize: 20 }}>{g.icon}</span>
                  <div>
                    <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>{g.label}</div>
                    <div style={{ fontSize: 13, color: 'var(--text-primary)', fontWeight: 600 }}>{g.value}</div>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </>
      )}

      {/* Weather card */}
      <Card style={{ padding: 'var(--sp-4) var(--sp-3)' }}>
        <CardLabel>Weather (OpenWeather)</CardLabel>
        <div style={{ display: 'flex', gap: 'var(--sp-2)', marginBottom: 'var(--sp-3)', flexWrap: 'wrap' }}>
          {[{ id: 'workout', label: 'By workout GPS' }, { id: 'city', label: 'By city' }].map(opt => (
            <button key={opt.id} onClick={() => setWeatherSource(opt.id)} style={{
              background:   weatherSource === opt.id ? 'rgba(232,168,50,0.12)' : 'var(--bg-overlay)',
              border:       `1px solid ${weatherSource === opt.id ? 'rgba(232,168,50,0.45)' : 'var(--border-subtle)'}`,
              borderRadius: 'var(--r-sm)', padding: '4px 10px', fontSize: 11,
              color:        weatherSource === opt.id ? 'var(--accent)' : 'var(--text-secondary)',
              fontFamily:   'var(--font-mono)', cursor: 'pointer',
            }}>{opt.label}</button>
          ))}
        </div>
        {weatherSource === 'city' && (
          <div style={{ display: 'flex', gap: 'var(--sp-2)', marginBottom: 'var(--sp-3)' }}>
            <input value={cityInput} onChange={e => setCityInput(e.target.value)} onKeyDown={e => e.key === 'Enter' && applyCity()} placeholder="City name…"
              style={{ flex: 1, background: 'var(--bg-raised)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: '5px 10px', color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 12 }} />
            <button onClick={applyCity} style={{ background: 'rgba(96,165,250,0.12)', border: '1px solid rgba(96,165,250,0.35)', borderRadius: 'var(--r-sm)', padding: '5px 12px', color: '#60a5fa', fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer' }}>Go</button>
          </div>
        )}
        {weather.loading && <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)' }}>Loading weather…</div>}
        {weather.error  && <div style={{ fontSize: 11, color: '#ef4444', fontFamily: 'var(--font-mono)' }}>{weather.error}</div>}
        {!weather.loading && weather.location && <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 'var(--sp-2)' }}>📍 {weather.location}</div>}
        {!weather.loading && weather.days.length > 0 && (
          <div style={{ display: 'flex', gap: 'var(--sp-2)', overflowX: 'auto', paddingBottom: 4 }}>
            {weather.days.map((d, i) => (
              <div key={i} style={{ minWidth: 72, background: 'var(--bg-raised)', border: '1px solid var(--border-subtle)', borderRadius: 'var(--r-sm)', padding: 'var(--sp-2)', flexShrink: 0 }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'var(--font-mono)', marginBottom: 2 }}>{i === 0 ? 'Today' : i === 1 ? 'Tomorrow' : `Day ${i + 1}`}</div>
                <div style={{ fontSize: 12, color: 'var(--text-secondary)' }}>{d.tempC}°C · {d.weatherLabel || '—'}</div>
                <div style={{ fontSize: 11, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)' }}>Wind: {d.windKmh} km/h, {d.windDir}</div>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
