-- Phase 1-3 analytics schema for coach-driven planning.
-- Safe/additive migration: creates new tables for profile, readiness, reflections, and aligned weekly plans.

-- 1) shared updated_at trigger function (idempotent)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 2) athlete profile
create table if not exists public.athlete_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  target_sport text not null default 'mixed'
    check (target_sport in ('mixed', 'running', 'cycling')),
  primary_goal text not null default '',
  goal_date date null,
  weekly_hours numeric(4,1) not null default 6.0
    check (weekly_hours > 0 and weekly_hours <= 40),
  constraints text not null default '',
  injury_notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_athlete_profiles_updated_at on public.athlete_profiles;
create trigger trg_athlete_profiles_updated_at
before update on public.athlete_profiles
for each row execute function public.set_updated_at();

-- 3) daily readiness checkins
create table if not exists public.daily_readiness_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null,
  sleep_score smallint not null default 70 check (sleep_score between 0 and 100),
  health_score smallint not null default 75 check (health_score between 0 and 100),
  weather_score smallint not null default 70 check (weather_score between 0 and 100),
  energy smallint not null default 6 check (energy between 1 and 10),
  motivation smallint not null default 7 check (motivation between 1 and 10),
  soreness smallint not null default 3 check (soreness between 1 and 10),
  stress smallint not null default 4 check (stress between 1 and 10),
  resting_hr_delta smallint not null default 0 check (resting_hr_delta between -30 and 50),
  sleep_hours numeric(4,1) not null default 7.5 check (sleep_hours between 0 and 24),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, checkin_date)
);

drop trigger if exists trg_daily_readiness_checkins_updated_at on public.daily_readiness_checkins;
create trigger trg_daily_readiness_checkins_updated_at
before update on public.daily_readiness_checkins
for each row execute function public.set_updated_at();

-- 4) workout reflections / notes
create table if not exists public.workout_reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workout_id bigint null,
  workout_date date null,
  purpose text not null default '',
  rpe smallint not null default 6 check (rpe between 1 and 10),
  pain smallint not null default 1 check (pain between 1 and 10),
  felt text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ux_workout_reflections_user_workout_id
  on public.workout_reflections(user_id, workout_id)
  where workout_id is not null;

create unique index if not exists ux_workout_reflections_user_workout_date
  on public.workout_reflections(user_id, workout_date)
  where workout_id is null and workout_date is not null;

drop trigger if exists trg_workout_reflections_updated_at on public.workout_reflections;
create trigger trg_workout_reflections_updated_at
before update on public.workout_reflections
for each row execute function public.set_updated_at();

-- 5) weekly aligned plans + coach prescription snapshots
create table if not exists public.coach_weekly_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start_date date not null,
  plan_sport text not null default 'mixed'
    check (plan_sport in ('mixed', 'running', 'cycling')),
  coherence_score smallint not null default 0 check (coherence_score between 0 and 100),
  required_readiness smallint not null default 0 check (required_readiness between 0 and 100),
  chosen_readiness smallint not null default 0 check (chosen_readiness between 0 and 100),
  fallback_used boolean not null default false,
  alignment_reason text not null default '',
  prescription jsonb not null default '{}'::jsonb,
  aligned_days jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, week_start_date, plan_sport)
);

drop trigger if exists trg_coach_weekly_plans_updated_at on public.coach_weekly_plans;
create trigger trg_coach_weekly_plans_updated_at
before update on public.coach_weekly_plans
for each row execute function public.set_updated_at();

-- 6) indexes
create index if not exists idx_daily_readiness_checkins_user_date
  on public.daily_readiness_checkins(user_id, checkin_date desc);

create index if not exists idx_workout_reflections_user_date
  on public.workout_reflections(user_id, workout_date desc nulls last);

create index if not exists idx_coach_weekly_plans_user_week
  on public.coach_weekly_plans(user_id, week_start_date desc, plan_sport);

-- 7) RLS
alter table public.athlete_profiles enable row level security;
alter table public.daily_readiness_checkins enable row level security;
alter table public.workout_reflections enable row level security;
alter table public.coach_weekly_plans enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'athlete_profiles' and policyname = 'athlete_profiles_owner_all'
  ) then
    create policy athlete_profiles_owner_all
      on public.athlete_profiles
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'daily_readiness_checkins' and policyname = 'daily_readiness_checkins_owner_all'
  ) then
    create policy daily_readiness_checkins_owner_all
      on public.daily_readiness_checkins
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'workout_reflections' and policyname = 'workout_reflections_owner_all'
  ) then
    create policy workout_reflections_owner_all
      on public.workout_reflections
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'coach_weekly_plans' and policyname = 'coach_weekly_plans_owner_all'
  ) then
    create policy coach_weekly_plans_owner_all
      on public.coach_weekly_plans
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
