-- Phases 1, 5, 8: mesocycles, lab values, medical documents, athlete profile medical column.
-- Additive/idempotent migration.

-- ── 1) athlete_profiles: medical_profile column ──────────────────────────────
-- Stores all medical profile fields as a single jsonb blob to avoid schema churn
-- as the medical form evolves.
alter table public.athlete_profiles
  add column if not exists medical_profile jsonb not null default '{}'::jsonb;

-- ── 2) medical_documents ─────────────────────────────────────────────────────
-- Stores uploaded medical documents (lab results, ECG, imaging, prescriptions).
-- Actual file bytes live in Supabase Storage bucket "medical-docs".
create table if not exists public.medical_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  file_name text not null,
  file_type text not null default '',
  file_size_bytes bigint not null default 0,
  storage_path text not null,
  category text not null default 'other'
    check (category in ('lab_results','ecg','imaging','prescription','discharge','referral','other')),
  description text not null default '',
  key_findings text not null default '',
  share_with_coach boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_medical_documents_updated_at on public.medical_documents;
create trigger trg_medical_documents_updated_at
before update on public.medical_documents
for each row execute function public.set_updated_at();

create index if not exists idx_medical_documents_user_created
  on public.medical_documents(user_id, created_at desc);

create index if not exists idx_medical_documents_user_shared
  on public.medical_documents(user_id, share_with_coach)
  where share_with_coach = true;

alter table public.medical_documents enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'medical_documents' and policyname = 'medical_documents_owner_all'
  ) then
    create policy medical_documents_owner_all
      on public.medical_documents
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

-- ── 3) mesocycles ────────────────────────────────────────────────────────────
-- Stores the AI-generated multi-week periodization plan.
-- One active mesocycle per user; older ones kept for history with is_active=false.
create table if not exists public.mesocycles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  goal_date date null,
  goal_description text null,
  total_weeks smallint not null default 8 check (total_weeks between 4 and 52),
  weeks jsonb not null default '[]'::jsonb,
  meta jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_mesocycles_updated_at on public.mesocycles;
create trigger trg_mesocycles_updated_at
before update on public.mesocycles
for each row execute function public.set_updated_at();

-- Only one active mesocycle per user.
create unique index if not exists ux_mesocycles_user_active
  on public.mesocycles(user_id)
  where is_active = true;

create index if not exists idx_mesocycles_user_created
  on public.mesocycles(user_id, created_at desc);

alter table public.mesocycles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'mesocycles' and policyname = 'mesocycles_owner_all'
  ) then
    create policy mesocycles_owner_all
      on public.mesocycles
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

-- ── 4) lab_values ────────────────────────────────────────────────────────────
-- Structured lab marker values extracted from medical documents via AI.
-- One row per (document, marker) pair; can also be entered manually (document_id null).
create table if not exists public.lab_values (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  document_id bigint null references public.medical_documents(id) on delete set null,
  test_date date not null,
  marker text not null,          -- e.g. 'ferritin', 'hemoglobin', 'vitamin_d'
  value numeric(10,3) not null,
  unit text not null default '',
  reference_low numeric(10,3) null,
  reference_high numeric(10,3) null,
  is_flagged boolean not null default false,
  created_at timestamptz not null default now()
);

-- Upsert key: one value per document per marker (null document_id = manual entry,
-- handled separately by user_id + marker + test_date).
create unique index if not exists ux_lab_values_document_marker
  on public.lab_values(document_id, marker)
  where document_id is not null;

create index if not exists idx_lab_values_user_marker_date
  on public.lab_values(user_id, marker, test_date desc);

create index if not exists idx_lab_values_user_date
  on public.lab_values(user_id, test_date desc);

alter table public.lab_values enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lab_values' and policyname = 'lab_values_owner_all'
  ) then
    create policy lab_values_owner_all
      on public.lab_values
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;
