-- Phase 2 unified coach architecture schema.
-- Additive/idempotent migration: global/action chat typing, coach cache table,
-- and persisted athlete coach digest.

-- 1) chat_messages: conversation typing for workout/global/action flows
alter table public.chat_messages
  add column if not exists conversation_type text;

-- Backfill existing rows only when conversation_type is missing.
update public.chat_messages
set conversation_type = case
  when workout_id is null then 'global'
  else 'workout'
end
where conversation_type is null;

alter table public.chat_messages
  alter column conversation_type set default 'workout';

alter table public.chat_messages
  alter column conversation_type set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chat_messages_conversation_type_check'
      and conrelid = 'public.chat_messages'::regclass
  ) then
    alter table public.chat_messages
      add constraint chat_messages_conversation_type_check
      check (conversation_type in ('workout', 'global', 'action'));
  end if;
end $$;

create index if not exists idx_chat_messages_user_conv_created
  on public.chat_messages(user_id, conversation_type, created_at desc);

-- 2) server-side cache for expensive/periodic coach outputs
create table if not exists public.coach_cache (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cache_key text not null,
  content text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  unique (user_id, cache_key)
);

create index if not exists idx_coach_cache_user_expires
  on public.coach_cache(user_id, expires_at);

create index if not exists idx_coach_cache_expires
  on public.coach_cache(expires_at);

alter table public.coach_cache enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'coach_cache' and policyname = 'coach_cache_owner_all'
  ) then
    create policy coach_cache_owner_all
      on public.coach_cache
      for all
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;
end $$;

-- 3) persist compact athlete digest server-side for unified prompt composition
alter table public.athlete_profiles
  add column if not exists coach_digest text not null default '';
