-- Track explicit login/logout events from client auth flows.
-- Additive migration.

create table if not exists public.auth_session_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('login', 'logout')),
  client_tz text null,
  user_agent text null,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_auth_session_events_user_occurred
  on public.auth_session_events(user_id, occurred_at desc);

alter table public.auth_session_events enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'auth_session_events' and policyname = 'auth_session_events_owner_read'
  ) then
    create policy auth_session_events_owner_read
      on public.auth_session_events
      for select
      using (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'auth_session_events' and policyname = 'auth_session_events_owner_insert'
  ) then
    create policy auth_session_events_owner_insert
      on public.auth_session_events
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;
